/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001d33",
        "surface-container-low": "#f1f4fa",
        "surface-variant": "#dfe3e9",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#663e00",
        "on-primary-container": "#fdfcff",
        "on-secondary-fixed-variant": "#2c4770",
        "surface-dim": "#d7dae1",
        "inverse-surface": "#2d3136",
        "secondary-container": "#b3cdfe",
        "surface-bright": "#f7f9ff",
        "on-primary": "#ffffff",
        "edutech-cyan": "#00AEEF",
        "outline-variant": "#bfc7d2",
        "on-error-container": "#93000a",
        "surface-gray": "#F8FAFC",
        "trust-navy": "#1A365D",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#3c5781",
        "surface": "#f7f9ff",
        "surface-container": "#ebeef4",
        "primary-container": "#007abd",
        "on-primary-fixed-variant": "#004a76",
        "on-surface-variant": "#3f4851",
        "on-tertiary-fixed": "#2b1700",
        "on-surface": "#181c21",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001b3d",
        "surface-container-highest": "#dfe3e9",
        "primary-fixed": "#cee5ff",
        "on-background": "#181c21",
        "inverse-on-surface": "#eef1f7",
        "secondary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#ffb963",
        "on-error": "#ffffff",
        "background": "#f7f9ff",
        "secondary": "#455f8a",
        "error": "#ba1a1a",
        "primary": "#006097",
        "action-orange": "#F6921E",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#adc7f8",
        "tertiary-container": "#a56700",
        "inverse-primary": "#96cbff",
        "tertiary": "#835100",
        "surface-container-high": "#e5e8ef",
        "primary-fixed-dim": "#96cbff",
        "tertiary-fixed": "#ffddb9",
        "on-secondary": "#ffffff",
        "outline": "#707882",
        "surface-tint": "#00639b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "20px",
        "unit": "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
